  -keep class hr.algebra.dnd5e.** { *; }
  -keepattributes Signature
  -keepattributes *Annotation*
  -keep class retrofit2.** { *; }
  -keep class okhttp3.** { *; }
  -keep class com.google.gson.** { *; }
  -keep public class * implements com.bumptech.glide.module.GlideModule
  -keep class * extends com.bumptech.glide.module.AppGlideModule { <init>(...); }